# 植生データの解析

## データの種類

- 組成データ：地点，階層，種名，被度など
- 地点データ：地点，緯度，経度，標高，日時など
- 種データ：種名，科，生活型，機能型など

  # 組成データは一般的には
  # 植物の状態として例えば実生，開花の有無などを記録することもあるでしょう．

  # 地点データは
  # 地形，天候など

  # 種データは
  # 系統

## パソコンへの入力

- スプレッドシートに入力
- 組成，地点，種のそれぞれのデータを1シートに入力
- 1行目は項目名
- 行や列を空けない
- tidyにする


## 解析の種類

- 多様性指数：α，β，γ
    - S, H', 1/d, D, Jなど
- 序列化(Ordination)：
- 分類
    - クラスター分析
    - TwinSpan
    - 分類回帰樹木
- Rarefaction Curve
- 指標種分析(IndVal or ISA：Indicator Species Analsis)

GISなどもある


## 被度

- 在・不在
- Braun-Blanquetの階級値
- 百分率
- その他もある(DAVE参照?)


```{r}
tbl <- tibble::tribble(
  ~"在・不在" , ~"B-B階級値", ~"百分率" , ~"百分率の代表値", 
  "1"         , "5"         , "75-"     , "87.5"         , 
  "1"         , "4"         , "50-"     , "62.5"         , 
  "1"         , "3"         , "25-"     , "37.5"         , 
  "1"         , "2"         , "10-"     , "17.5"         , 
  "1"         , "1"         , "1-"      ,  "5.0"         , 
  "1"         , "+"         , " -0"     , "0.1"          , 
  "1"         , "r"         , " -0"     , "0.01?"        , 
  "0"         , "-"         , "0"       , "0"            )
```


  # 生態調査法(鈴木時夫 p61)
  # 星野(1991)，03479.pdf参照


## 類似度

- bray-curtis
- ユークリッド距離
- マンハッタン距離
- correlation
- QS = 2a / (2a+b+c), Sorensen
- CC = a / (a+b+c), Jaccard
φ = (ad - bc) / ((a+b)(a+c)(b+d)(c+d))

「生物群集の多変量解析」小林四郎 p26

## クラスター分析

- 結合方法が色々ある
- 最近隣方式
- 最遠隣方式
- 重心方式
- 群平均法
  非加重，加重

結びつけていく
1次元的


## 序列化，Ordination

- PCA，主成分分析
- DCA
- nMDS
- CCA
- RDA

2次元への位置づけ
本当は多次元だけど，実質的に使うのは影響の大きい最初の2次元だけ


## 文献

伊藤 秀三(編). 2003. 群落の組成と構造. 朝倉書店. 

1977年に出版され，その後長らく絶版になっていた．
2003年に復刊されたものの，これもすでに絶版である．
大手ネット書店ではやや高値で中古が取引されている．

小林 四郎. 1995. 生物群集の多変量解析. 蒼樹書房. 

Wildi, O. 2017. Data Analysis in Vegetation Ecology, 3rd ed. Cabi.

佐々木 雄大・小山 明日香・小柳 知代・古川 拓哉・内田 圭. 2015. 生物群集の構造と多様性の解析. 共立出版. 

土居 秀幸・岡村 寛. 2011. 生物群集解析のための類似度とその応用: Rを使った類似度の算出, グラフ化, 検定. 日本生態学会誌, 61, 3-20. 

