  # Install packages (need only once)
if(!require("devtools"))        install.packages("devtools")
                                devtools::install_github("matutosi/ecan", force = TRUE)
if(!require("cluster"))         install.packages("cluster")
if(!require("dave"))            install.packages("dave")
if(!require("dendextend"))      install.packages("dendextend")
if(!require("ggdendro"))        install.packages("ggdendro")
if(!require("graphics"))        install.packages("graphics")
if(!require("labdsv"))          install.packages("labdsv")
if(!require("magrittr"))        install.packages("magrittr")
if(!require("pkgload"))         install.packages("pkgload")
if(!require("reactable"))       install.packages("reactable")
if(!require("rlang"))           install.packages("rlang")
if(!require("rmarkdown"))       install.packages("rmarkdown")
if(!require("shiny"))           install.packages("shiny")
if(!require("shinycssloaders")) install.packages("shinycssloaders")
if(!require("tidyverse"))       install.packages("tidyverse")
if(!require("vegan"))           install.packages("vegan")

  # ui.R
  # server.R
  # source("server.R")
  # source("ui.R")
source("cluster.R")
source("data_download.R")
source("diversity.R")
source("ind_val.R")
source("load_data.R")
source("ordination.R")
