  # https://matutosi.shinyapps.io/ecanvis/
if(!require("devtools"))        install.packages("devtools")
if(!require("ecan"))            devtools::install_github("matutosi/ecan")
if(1 >= compareVersion(as.character(packageVersion("ecan")), "0.1.0"))
                                devtools::install_github("matutosi/ecan", force = TRUE)
if(!require("cluster"))         install.packages("cluster")
if(!require("dave"))            install.packages("dave")
if(!require("dendextend"))      install.packages("dendextend")
if(!require("ggdendro"))        install.packages("ggdendro")
if(!require("graphics"))        install.packages("graphics")
if(!require("labdsv"))          install.packages("labdsv")
if(!require("magrittr"))        install.packages("magrittr")
if(!require("pkgload"))         install.packages("pkgload")
if(!require("reactable"))       install.packages("reactable")
if(!require("rlang"))           install.packages("rlang")
if(!require("rmarkdown"))       install.packages("rmarkdown")
if(!require("shiny"))           install.packages("shiny")
if(!require("shinycssloaders")) install.packages("shinycssloaders")
if(!require("tidyverse"))       install.packages("tidyverse")
if(!require("vegan"))           install.packages("vegan")

library(ecan)
library(vegan)
library(tidyverse)
library(shiny)
library(zeallot)
library(dendextend)

source("data_load.R")
source("data_example.R")
source("data_download.R")
source("diversity.R")
source("ind_val.R")
source("cluster.R")
source("ordination.R")
