name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.MY_GITHUB_TOKEN }}
    steps:
      - run: echo "Hello, world!"
      - uses: actions/checkout@v4
